apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  findsecbugs-hybrid-scan:
    steps:        
      - name: checkout Source Code
        uses: cloudbees-io/checkout@v2

      - name: findsec hybrid plugin scan
        uses: ./
        with:
          # The path used in the previous step to create the tar file
          binary-tar-path: ./vulnerablesqlapp.tar

  GO-Test:
    steps:        
      - name: checkout-source-code
        uses: cloudbees-io/checkout@v2
      
      - name: GO-Test
        uses: cloudbees-io/publish-test-results@v2
        with:
          test-type: go
          results-path: ${{ cloudbees.workspace }}/test_data/go/report2.xml

      - name: Build
        id: build
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          sleep 20
          # Create a hash based on current time & random data
          hash=$(date +%s%N | sha256sum | awk '{print $1}')
          echo "Generated hash: $hash"

          # Make it available to other steps
          echo "$hash" >> $CLOUDBEES_OUTPUTS/hash
      
      - name: Register build artifact
        id: publish-build-1
        uses: cloudbees-io/register-build-artifact@v2
        with:
          version: ${{cloudbees.version}}
          url: docker.io/library/shas/test-1
          name: test-artifact-ninja-1:${{cloudbees.version}}
  
  deploy-test:
    environment: Production
    steps:
      - name: Say hello
        uses: docker://alpine:3.17
        kind: deploy
        shell: sh
        run: |
          echo "hello world 1"